# Домашнее задание «Функции и работа с данными»

# Задание 1

In [19]:
import pandas as pd

In [20]:
data = pd.read_csv('ml-latest-small/ratings.csv')
datamov = pd.read_csv('ml-latest-small/movies.csv')

obj = data.groupby('movieId').mean()

In [21]:
def rate(row):
    if 0 <= row['rating'] <= 2:
        return 'Низкий рейтинг'
    elif 2 < row['rating'] <= 4:
        return 'Средний рейтинг'
    elif row['rating'] == 5 or row['rating'] == 4.5:
        return 'Высокий рейтинг'
    return 'Рейтинг неопределен'

obj['class'] = obj.apply(rate, axis=1)
obj.head(10)
#datamov['class2'] = datamov.apply(rate, axis=1)
#datamov.tail(40)

# Не догнал тут, как записать результат в столбец class в файл datamov, смэтчив их по movieId

             userId    rating     timestamp            class
movieId
1        338.558704  3.872470  1.103116e+09  Средний рейтинг
2        318.906542  3.401869  1.069321e+09  Средний рейтинг
3        374.423729  3.161017  9.662429e+08  Средний рейтинг
4        355.538462  2.384615  9.277797e+08  Средний рейтинг
5        320.785714  3.267857  9.967201e+08  Средний рейтинг
6        334.096154  3.884615  1.001189e+09  Средний рейтинг
7        321.924528  3.283019  9.575076e+08  Средний рейтинг
8        213.400000  3.800000  9.424714e+08  Средний рейтинг
9        277.100000  3.150000  8.715075e+08  Средний рейтинг
10       316.131148  3.450820  9.977456e+08  Средний рейтинг

# Задание 2

In [1]:
import pandas as pd
data1 = pd.read_csv('keywords.csv')
data1.head(5)

         keyword     shows
0             вк  64292779
1  одноклассники  63810309
2         москва  41747114
3           ютуб  39995567
4      вконтакте  21014195

In [2]:
geo_data = {

    'Центр': ['москва', 'тула', 'ярославль'],

    'Северо-Запад': ['петербург', 'псков', 'мурманск'],

    'Дальний Восток': ['владивосток', 'сахалин', 'хабаровск']

    }
pd_geo = pd.DataFrame(geo_data)
pd_geo.head(10)

       Центр Северо-Запад Дальний Восток
0     москва    петербург    владивосток
1       тула        псков        сахалин
2  ярославль     мурманск      хабаровск

In [3]:
def ger(row):

    i = 0
    for k, e in geo_data.items():
               
        if geo_data['Центр'][i] in row['keyword']:
            return 'Центр'
        
        if geo_data['Северо-Запад'][i] in row['keyword']:
            return 'Северо-Запад'
        
        if geo_data['Дальний Восток'][i] in row['keyword']:
            return 'Дальний Восток'
        
        i = i + 1
ger(data1)
data1['region'] = data1.apply(ger, axis=1)
data1.head(30)

                          keyword     shows          region
0                              вк  64292779            None
1                   одноклассники  63810309            None
2                          москва  41747114           Центр
3                            ютуб  39995567            None
4                       вконтакте  21014195            None
5      одноклассники моя страница  19976138            None
6                            майл  15144673            None
7                           авито  14786593            None
8                      переводчик  14453469            None
9                          яндекс  13344734            None
10                сбербанк онлайн  10725673            None
11                    владивосток   7687204  Дальний Восток
12                           игры   6075762            None
13                          псков   5729958    Северо-Запад
14         вконтакте моя страница   5971451            None
15                           секс   5431732            None
16                        сахалин   5175471  Дальний Восток
17                             dr   4880955            None
18                      петербург   4879645    Северо-Запад
19                        рамблер   4540421            None
20                    фильмы 2016   4486635            None
21                         погода   4344510            None
22                             vk   4330448            None
23              ютуб видеохостинг   4215267            None
24                          дойки   4133424            None
25  одноклассники социальная сеть   4018230            None
26                       мультики   3866664            None
27                        контакт   3815111            None
28                        фейсбук   3669993            None
29                    порно видео   3858938            None

In [99]:
i = 0

def ger(row, rows):
    
    i = 0
    rows = rows['keyword']
    row = row['Центр'][i]
    

    i = i + 1
    if row['Центр'][i] in rows:
        print (row['Центр'][i])
      # i = i + 1
        i = i + 1
data1.head(10)

ger(pd_geo, data1)
data1['region'] = data1.apply(ger, axis=1)

# застрял тут

TypeError: string indices must be integers