# Задание 1

Обязательная часть
Будем осуществлять работу с непростым набором данных о состоянии здоровья лошадей, испытывающих кишечные колики.

Задание 1. Базовое изучение
Изучить представленный набор данных на основе описания его столбцов и выбрать 8 столбцов для дальнейшего изучения (среди них должны быть как числовые, так и категориальные). Провести расчет базовых метрик для них, кратко описать результаты.

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('horse_data.csv')
names = ['surgery', 'Age', 'Hospital Number', 'rectal temperature', 'pulse', 'respiratory rate', 'temperature of extremities', 'peripheral pulse', 'mucous membranes', 'capillary refill time', 'pain', 'peristalsis', 'abdominal distension', 'nasogastric tube', 'nasogastric reflux', 'nasogastric reflux PH', 'rectal examination', 'abdomen', 'packed cell volume', 'total protein', 'abdominocentesis appearance', 'abdomcentesis total protein', 'outcome', 'surgical lesion', 'type of lesion1', 'type of lesion2', 'type of lesion3', 'cp_data']

In [3]:
df = pd.read_csv('horse_data.csv', names = names, na_values = '?')
df = df.apply(pd.to_numeric)
df

,surgery,Age,Hospital Number,rectal temperature,pulse,respiratory rate,temperature of extremities,peripheral pulse,mucous membranes,capillary refill time,...,packed cell volume,total protein,abdominocentesis appearance,abdomcentesis total protein,outcome,surgical lesion,type of lesion1,type of lesion2,type of lesion3,cp_data
0,2.0,1,530101,38.5,66.0,28.0,3.0,3.0,NaN,2.0,...,45.0,8.4,NaN,NaN,2.0,2,11300,0,0,2
1,1.0,1,534817,39.2,88.0,20.0,NaN,NaN,4.0,1.0,...,50.0,85.0,2.0,2.0,3.0,2,2208,0,0,2
2,2.0,1,530334,38.3,40.0,24.0,1.0,1.0,3.0,1.0,...,33.0,6.7,NaN,NaN,1.0,2,0,0,0,1
3,1.0,9,5290409,39.1,164.0,84.0,4.0,1.0,6.0,2.0,...,48.0,7.2,3.0,5.3,2.0,1,2208,0,0,1
4,2.0,1,530255,37.3,104.0,35.0,NaN,NaN,6.0,2.0,...,74.0,7.4,NaN,NaN,2.0,2,4300,0,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
295,1.0,1,533886,NaN,120.0,70.0,4.0,NaN,4.0,2.0,...,55.0,65.0,NaN,NaN,3.0,2,3205,0,0,2
296,2.0,1,527702,37.2,72.0,24.0,3.0,2.0,4.0,2.0,...,44.0,NaN,3.0,3.3,3.0,1,2208,0,0,1
297,1.0,1,529386,37.5,72.0,30.0,4.0,3.0,4.0,1.0,...,60.0,6.8,NaN,NaN,2.0,1,3205,0,0,2
298,1.0,1,530612,36.5,100.0,24.0,3.0,3.0,3.0,1.0,...,50.0,6.0,3.0,3.4,1.0,1,2208,0,0,1
299,1.0,1,534618,37.2,40.0,20.0,NaN,NaN,NaN,NaN,...,36.0,62.0,1.0,1.0,3.0,2,6112,0,0,2

методом describe вычисляем почти все нужные нам метрики
count - количество элементов в столбце
mean - среднее значение
std - стандартное квадратичное отклонение
минимальные, максимальные значения
процентили и медиана

для категориальных значний, типа возраста,

In [4]:
df.describe().round(2)

,surgery,Age,Hospital Number,rectal temperature,pulse,respiratory rate,temperature of extremities,peripheral pulse,mucous membranes,capillary refill time,...,packed cell volume,total protein,abdominocentesis appearance,abdomcentesis total protein,outcome,surgical lesion,type of lesion1,type of lesion2,type of lesion3,cp_data
count,299.00,300.00,300.00,240.00,276.00,242.00,244.00,231.00,253.00,268.00,...,271.00,267.00,135.00,102.00,299.00,300.00,300.00,300.00,300.00,300.00
mean,1.40,1.64,1085888.83,38.17,71.91,30.42,2.35,2.02,2.85,1.31,...,46.30,24.46,2.04,3.02,1.55,1.36,3657.88,90.23,7.36,1.67
std,0.49,2.17,1529800.91,0.73,28.63,17.64,1.05,1.04,1.62,0.48,...,10.42,27.48,0.80,1.97,0.74,0.48,5399.51,649.57,127.54,0.47
min,1.00,1.00,518476.00,35.40,30.00,8.00,1.00,1.00,1.00,1.00,...,23.00,3.30,1.00,0.10,1.00,1.00,0.00,0.00,0.00,1.00
25%,1.00,1.00,528904.00,37.80,48.00,18.50,1.00,1.00,1.00,1.00,...,38.00,6.50,1.00,2.00,1.00,1.00,2111.75,0.00,0.00,1.00
50%,1.00,1.00,530305.50,38.20,64.00,24.50,3.00,2.00,3.00,1.00,...,45.00,7.50,2.00,2.25,1.00,1.00,2673.50,0.00,0.00,2.00
75%,2.00,1.00,534727.50,38.50,88.00,36.00,3.00,3.00,4.00,2.00,...,52.00,57.00,3.00,3.90,2.00,2.00,3209.00,0.00,0.00,2.00
max,2.00,9.00,5305629.00,40.80,184.00,96.00,4.00,4.00,6.00,3.00,...,75.00,89.00,3.00,10.10,3.00,2.00,41110.00,7111.00,2209.00,2.00

посчитаем моду - наиболее встречаемый элемент в столбце

In [5]:
print('Значение моды surgery: ', df['surgery'].round().mode()[0]) #категориальный
print('Значение моды respiratory rate: ', df['respiratory rate'].round().mode()[0]) #категориальный
print('Значение моды Age: ', df['Age'].round().mode()[0]) #категориальный
print('Значение моды mucous membranes: ', df['mucous membranes'].round().mode()[0]) #категориальный
print('Значение моды total protein: ', df['total protein'].round().mode()[0]) #дискретный
print('Значение моды rectal temperature: ', df['rectal temperature'].round().mode()[0]) #непрерывная
print('Значение моды abdomcentesis total protein: ', df['abdomcentesis total protein'].round().mode()[0]) #дискретный
print('Значение моды capillary refill time: ', df['capillary refill time'].round().mode()[0]) #категориальный
print('Значение моды pulse: ', df['pulse'].round().mode()[0]) #дискретный

Значение моды surgery:  1.0
Значение моды respiratory rate:  20.0
Значение моды Age:  1
Значение моды mucous membranes:  1.0
Значение моды total protein:  7.0
Значение моды rectal temperature:  38.0
Значение моды abdomcentesis total protein:  2.0
Значение моды capillary refill time:  1.0
Значение моды pulse:  48.0

# Задание 2

In [6]:
# Посчитаем выбросы surgery
q1 = df.surgery.quantile(0.25)
q3 = df.surgery.quantile(0.75)
iqr = q3 - q1
lower_bound = q1 - (1.5 * iqr) 
upper_bound = q3 + (1.5 * iqr)
remove_outliers = df[df.surgery.between(lower_bound, upper_bound, inclusive=True)].sort_values('surgery')
remove_outliers

,surgery,Age,Hospital Number,rectal temperature,pulse,respiratory rate,temperature of extremities,peripheral pulse,mucous membranes,capillary refill time,...,packed cell volume,total protein,abdominocentesis appearance,abdomcentesis total protein,outcome,surgical lesion,type of lesion1,type of lesion2,type of lesion3,cp_data
299,1.0,1,534618,37.2,40.0,20.0,NaN,NaN,NaN,NaN,...,36.0,62.0,1.0,1.0,3.0,2,6112,0,0,2
128,1.0,1,535330,37.4,84.0,20.0,NaN,NaN,3.0,1.0,...,31.0,61.0,NaN,1.0,3.0,2,2208,0,0,2
129,1.0,1,527698,38.4,49.0,NaN,NaN,NaN,1.0,1.0,...,44.0,7.6,NaN,NaN,1.0,1,2206,0,0,2
130,1.0,1,528964,37.8,30.0,12.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2.0,1,2113,0,0,2
242,1.0,1,530354,NaN,36.0,32.0,1.0,1.0,4.0,1.0,...,41.0,5.9,NaN,NaN,2.0,1,2205,0,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
147,2.0,1,530001,38.0,44.0,12.0,2.0,1.0,3.0,1.0,...,33.0,6.5,NaN,NaN,2.0,1,2209,0,0,2
149,2.0,1,535314,38.7,48.0,24.0,NaN,NaN,NaN,NaN,...,34.0,63.0,NaN,NaN,1.0,2,0,0,0,2
153,2.0,1,528804,38.6,48.0,20.0,3.0,1.0,1.0,1.0,...,50.0,7.3,1.0,NaN,1.0,2,3111,0,0,1
93,2.0,1,530310,NaN,NaN,NaN,3.0,3.0,1.0,1.0,...,38.0,6.5,NaN,NaN,2.0,1,3205,0,0,2
150,2.0,1,533793,38.9,44.0,14.0,3.0,1.0,1.0,1.0,...,33.0,64.0,NaN,NaN,1.0,2,0,0,0,2

In [7]:
pd.concat([df, remove_outliers]).drop_duplicates(keep=False)

,surgery,Age,Hospital Number,rectal temperature,pulse,respiratory rate,temperature of extremities,peripheral pulse,mucous membranes,capillary refill time,...,packed cell volume,total protein,abdominocentesis appearance,abdomcentesis total protein,outcome,surgical lesion,type of lesion1,type of lesion2,type of lesion3,cp_data
132,NaN,1,534572,38.0,48.0,20.0,3.0,1.0,3.0,1.0,...,43.0,73.0,2.0,1.0,NaN,1,3111,0,0,2

По surgery видим выбросы в виде отстутствующих значений 
все ок, оставляем

In [8]:
# Посчитаем выбросы Age
q1 = df.Age.quantile(0.25)
q3 = df.Age.quantile(0.75)
iqr = q3 - q1
lower_bound = q1 - (1.5 * iqr) 
upper_bound = q3 + (1.5 * iqr)
remove_outliers = df[df.Age.between(lower_bound, upper_bound, inclusive=True)].sort_values('Age')
remove_outliers

,surgery,Age,Hospital Number,rectal temperature,pulse,respiratory rate,temperature of extremities,peripheral pulse,mucous membranes,capillary refill time,...,packed cell volume,total protein,abdominocentesis appearance,abdomcentesis total protein,outcome,surgical lesion,type of lesion1,type of lesion2,type of lesion3,cp_data
0,2.0,1,530101,38.5,66.0,28.0,3.0,3.0,NaN,2.0,...,45.0,8.4,NaN,NaN,2.0,2,11300,0,0,2
189,1.0,1,5299603,38.3,60.0,16.0,3.0,1.0,1.0,1.0,...,30.0,6.0,1.0,3.0,1.0,1,31110,0,0,2
190,1.0,1,528742,37.1,40.0,8.0,NaN,1.0,4.0,1.0,...,23.0,6.7,3.0,NaN,1.0,1,3133,0,0,1
192,1.0,1,534788,38.2,48.0,18.0,1.0,1.0,1.0,1.0,...,48.0,74.0,1.0,2.0,1.0,1,5111,0,0,2
193,1.0,1,529373,NaN,60.0,48.0,3.0,3.0,4.0,2.0,...,58.0,7.6,NaN,NaN,2.0,1,3205,0,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100,1.0,1,535364,38.2,40.0,16.0,3.0,3.0,1.0,1.0,...,34.0,66.0,NaN,NaN,1.0,2,0,0,0,2
99,2.0,1,530002,39.6,108.0,51.0,3.0,3.0,6.0,2.0,...,59.0,8.0,2.0,2.6,1.0,2,4300,0,0,1
98,2.0,1,534135,37.7,44.0,40.0,2.0,1.0,3.0,1.0,...,41.0,60.0,NaN,NaN,1.0,2,0,0,0,2
105,1.0,1,530381,NaN,70.0,36.0,1.0,NaN,3.0,2.0,...,36.0,7.3,NaN,NaN,1.0,1,31110,0,0,2
299,1.0,1,534618,37.2,40.0,20.0,NaN,NaN,NaN,NaN,...,36.0,62.0,1.0,1.0,3.0,2,6112,0,0,2

In [9]:
pd.concat([df, remove_outliers]).drop_duplicates(keep=False)

,surgery,Age,Hospital Number,rectal temperature,pulse,respiratory rate,temperature of extremities,peripheral pulse,mucous membranes,capillary refill time,...,packed cell volume,total protein,abdominocentesis appearance,abdomcentesis total protein,outcome,surgical lesion,type of lesion1,type of lesion2,type of lesion3,cp_data
3,1.0,9,5290409,39.1,164.0,84.0,4.0,1.0,6.0,2.0,...,48.0,7.2,3.0,5.3,2.0,1,2208,0,0,1
9,2.0,9,5299629,38.3,90.0,NaN,1.0,NaN,1.0,1.0,...,40.0,6.2,1.0,2.2,1.0,2,0,0,0,1
13,2.0,9,5291329,38.0,92.0,28.0,1.0,1.0,2.0,1.0,...,37.0,6.1,1.0,NaN,2.0,2,0,0,0,1
16,1.0,9,5301219,NaN,128.0,36.0,3.0,3.0,4.0,2.0,...,53.0,7.8,3.0,4.7,2.0,2,1400,0,0,1
23,1.0,9,534998,38.3,130.0,60.0,NaN,3.0,NaN,1.0,...,50.0,70.0,NaN,NaN,1.0,1,3111,0,0,2
39,1.0,9,5277409,39.2,146.0,96.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2.0,1,2113,0,0,2
41,2.0,9,5288249,39.0,150.0,72.0,NaN,NaN,NaN,NaN,...,47.0,8.5,NaN,0.1,1.0,1,9400,0,0,1
55,1.0,9,5282839,38.6,160.0,20.0,3.0,NaN,5.0,1.0,...,38.0,NaN,2.0,NaN,2.0,1,7111,0,0,1
74,1.0,9,5292929,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,37.0,4.9,NaN,NaN,2.0,1,11124,0,0,2
75,1.0,9,534092,39.7,100.0,NaN,3.0,3.0,5.0,2.0,...,48.0,57.0,2.0,2.0,3.0,1,1400,0,0,2
82,1.0,9,5290759,38.1,100.0,80.0,3.0,1.0,2.0,1.0,...,36.0,5.7,NaN,NaN,1.0,1,3111,0,0,2
103,1.0,9,5292489,38.0,140.0,68.0,1.0,1.0,1.0,1.0,...,39.0,5.3,NaN,NaN,1.0,1,7111,0,0,2
109,1.0,9,5297379,38.4,84.0,40.0,3.0,3.0,2.0,1.0,...,36.0,6.6,2.0,2.8,2.0,1,2205,0,0,1
135,1.0,9,5287179,38.1,136.0,48.0,3.0,3.0,3.0,1.0,...,33.0,4.9,2.0,2.9,2.0,1,2205,0,0,1
191,2.0,9,5287279,NaN,100.0,44.0,2.0,1.0,1.0,1.0,...,37.0,4.7,NaN,NaN,1.0,2,7111,0,0,2
212,1.0,9,5294369,38.9,120.0,30.0,1.0,3.0,2.0,2.0,...,47.0,6.3,1.0,NaN,1.0,2,2124,0,0,2
227,1.0,9,5289419,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,45.0,6.5,2.0,NaN,1.0,1,9000,0,0,1
229,1.0,9,534597,38.5,120.0,70.0,NaN,NaN,NaN,NaN,...,35.0,54.0,1.0,1.0,1.0,1,4205,3111,2209,2
244,1.0,9,5291409,38.2,124.0,88.0,1.0,3.0,2.0,1.0,...,47.0,8.0,1.0,NaN,1.0,1,9400,0,0,1
252,1.0,9,5291719,38.8,124.0,36.0,3.0,1.0,2.0,1.0,...,50.0,7.6,3.0,NaN,2.0,1,2208,0,0,1
255,1.0,9,5294539,38.8,184.0,84.0,1.0,NaN,1.0,1.0,...,33.0,3.3,NaN,NaN,2.0,1,7111,0,0,2
262,2.0,9,5305629,38.6,88.0,28.0,NaN,NaN,NaN,NaN,...,35.0,5.9,NaN,NaN,1.0,2,0,0,0,2
275,1.0,9,5297159,38.8,150.0,50.0,1.0,3.0,6.0,2.0,...,50.0,6.2,NaN,NaN,2.0,1,4207,0,0,2
287,2.0,9,5305129,39.5,84.0,30.0,NaN,NaN,NaN,1.0,...,28.0,5.0,NaN,NaN,1.0,2,0,0,0,2

По Age видим выбросы в виде 9, скорее всего, это ошибка ввода данных и имеется ввиду 9 месяцев. Согласно справке заменим 9 на 1 - Adult horse

In [10]:
# Посчитаем выбросы Hospital Number
q1 = df['Hospital Number'].quantile(0.25)
q3 = df['Hospital Number'].quantile(0.75)
iqr = q3 - q1
lower_bound = q1 - (1.5 * iqr) 
upper_bound = q3 + (1.5 * iqr)
remove_outliers = df[df['Hospital Number'].between(lower_bound, upper_bound, inclusive=True)].sort_values('Hospital Number')
remove_outliers

,surgery,Age,Hospital Number,rectal temperature,pulse,respiratory rate,temperature of extremities,peripheral pulse,mucous membranes,capillary refill time,...,packed cell volume,total protein,abdominocentesis appearance,abdomcentesis total protein,outcome,surgical lesion,type of lesion1,type of lesion2,type of lesion3,cp_data
197,2.0,1,521399,38.5,96.0,36.0,3.0,3.0,NaN,2.0,...,70.0,8.5,NaN,NaN,2.0,1,1400,0,0,1
22,1.0,1,521681,38.6,42.0,34.0,2.0,1.0,4.0,NaN,...,48.0,7.2,NaN,NaN,1.0,1,3111,0,0,2
141,2.0,1,522979,36.0,42.0,30.0,NaN,NaN,5.0,1.0,...,64.0,6.8,NaN,NaN,2.0,2,1400,0,0,2
177,1.0,1,523190,NaN,68.0,14.0,NaN,NaN,4.0,1.0,...,NaN,NaN,2.0,2.8,2.0,1,4205,0,0,1
17,2.0,1,526639,37.5,48.0,24.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1.0,2,0,0,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100,1.0,1,535364,38.2,40.0,16.0,3.0,3.0,1.0,1.0,...,34.0,66.0,NaN,NaN,1.0,2,0,0,0,2
89,2.0,1,535381,38.3,42.0,10.0,1.0,1.0,1.0,1.0,...,38.0,61.0,NaN,NaN,1.0,2,0,0,0,2
224,1.0,1,535392,38.8,50.0,14.0,1.0,1.0,1.0,1.0,...,38.0,58.0,NaN,NaN,1.0,1,3111,0,0,2
44,1.0,1,535407,35.4,140.0,24.0,3.0,3.0,4.0,2.0,...,57.0,69.0,3.0,2.0,3.0,1,3205,0,0,2
29,2.0,1,535415,37.7,48.0,NaN,2.0,1.0,1.0,1.0,...,45.0,76.0,NaN,NaN,1.0,2,0,0,0,2

In [11]:
pd.concat([df, remove_outliers]).drop_duplicates(keep=False)

,surgery,Age,Hospital Number,rectal temperature,pulse,respiratory rate,temperature of extremities,peripheral pulse,mucous membranes,capillary refill time,...,packed cell volume,total protein,abdominocentesis appearance,abdomcentesis total protein,outcome,surgical lesion,type of lesion1,type of lesion2,type of lesion3,cp_data
3,1.0,9,5290409,39.1,164.0,84.0,4.0,1.0,6.0,2.0,...,48.0,7.2,3.0,5.3,2.0,1,2208,0,0,1
9,2.0,9,5299629,38.3,90.0,NaN,1.0,NaN,1.0,1.0,...,40.0,6.2,1.0,2.2,1.0,2,0,0,0,1
13,2.0,9,5291329,38.0,92.0,28.0,1.0,1.0,2.0,1.0,...,37.0,6.1,1.0,NaN,2.0,2,0,0,0,1
16,1.0,9,5301219,NaN,128.0,36.0,3.0,3.0,4.0,2.0,...,53.0,7.8,3.0,4.7,2.0,2,1400,0,0,1
18,1.0,1,5290481,37.6,64.0,21.0,1.0,1.0,2.0,1.0,...,40.0,7.0,1.0,NaN,1.0,1,4205,0,0,1
28,1.0,1,5279442,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2.0,2,4300,0,0,2
39,1.0,9,5277409,39.2,146.0,96.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2.0,1,2113,0,0,2
41,2.0,9,5288249,39.0,150.0,72.0,NaN,NaN,NaN,NaN,...,47.0,8.5,NaN,0.1,1.0,1,9400,0,0,1
55,1.0,9,5282839,38.6,160.0,20.0,3.0,NaN,5.0,1.0,...,38.0,NaN,2.0,NaN,2.0,1,7111,0,0,1
72,1.0,1,5299253,37.7,56.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2.0,1,2113,0,0,2
74,1.0,9,5292929,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,37.0,4.9,NaN,NaN,2.0,1,11124,0,0,2
82,1.0,9,5290759,38.1,100.0,80.0,3.0,1.0,2.0,1.0,...,36.0,5.7,NaN,NaN,1.0,1,3111,0,0,2
83,1.0,1,5279822,38.0,NaN,24.0,3.0,3.0,6.0,2.0,...,68.0,7.8,NaN,NaN,2.0,1,3205,0,0,2
103,1.0,9,5292489,38.0,140.0,68.0,1.0,1.0,1.0,1.0,...,39.0,5.3,NaN,NaN,1.0,1,7111,0,0,2
109,1.0,9,5297379,38.4,84.0,40.0,3.0,3.0,2.0,1.0,...,36.0,6.6,2.0,2.8,2.0,1,2205,0,0,1
117,2.0,1,5290482,39.5,NaN,NaN,3.0,3.0,4.0,2.0,...,NaN,6.7,1.0,NaN,3.0,1,4205,0,0,2
127,1.0,1,5262541,37.4,50.0,32.0,3.0,3.0,NaN,1.0,...,45.0,7.9,2.0,1.0,1.0,1,2208,0,0,1
135,1.0,9,5287179,38.1,136.0,48.0,3.0,3.0,3.0,1.0,...,33.0,4.9,2.0,2.9,2.0,1,2205,0,0,1
174,2.0,1,518476,NaN,NaN,NaN,3.0,4.0,6.0,NaN,...,NaN,NaN,NaN,NaN,2.0,1,3400,0,0,1
182,1.0,1,5279822,38.0,NaN,24.0,3.0,3.0,6.0,2.0,...,68.0,7.8,NaN,NaN,2.0,1,2205,0,0,2
186,1.0,1,5278331,39.3,64.0,90.0,2.0,3.0,1.0,1.0,...,39.0,6.7,NaN,NaN,1.0,1,21110,0,0,2
189,1.0,1,5299603,38.3,60.0,16.0,3.0,1.0,1.0,1.0,...,30.0,6.0,1.0,3.0,1.0,1,31110,0,0,2
191,2.0,9,5287279,NaN,100.0,44.0,2.0,1.0,1.0,1.0,...,37.0,4.7,NaN,NaN,1.0,2,7111,0,0,2
212,1.0,9,5294369,38.9,120.0,30.0,1.0,3.0,2.0,2.0,...,47.0,6.3,1.0,NaN,1.0,2,2124,0,0,2
217,1.0,1,5279441,38.0,76.0,18.0,NaN,NaN,NaN,2.0,...,71.0,11.0,NaN,NaN,1.0,1,2209,0,0,1
227,1.0,9,5289419,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,45.0,6.5,2.0,NaN,1.0,1,9000,0,0,1
232,1.0,1,5262543,38.5,30.0,18.0,NaN,NaN,NaN,NaN,...,40.0,7.7,NaN,NaN,1.0,1,2113,0,0,2
243,1.0,1,5281091,38.4,92.0,20.0,1.0,NaN,NaN,2.0,...,NaN,NaN,NaN,NaN,1.0,1,2208,0,0,1
244,1.0,9,5291409,38.2,124.0,88.0,1.0,3.0,2.0,1.0,...,47.0,8.0,1.0,NaN,1.0,1,9400,0,0,1
252,1.0,9,5291719,38.8,124.0,36.0,3.0,1.0,2.0,1.0,...,50.0,7.6,3.0,NaN,2.0,1,2208,0,0,1
255,1.0,9,5294539,38.8,184.0,84.0,1.0,NaN,1.0,1.0,...,33.0,3.3,NaN,NaN,2.0,1,7111,0,0,2
262,2.0,9,5305629,38.6,88.0,28.0,NaN,NaN,NaN,NaN,...,35.0,5.9,NaN,NaN,1.0,2,0,0,0,2
275,1.0,9,5297159,38.8,150.0,50.0,1.0,3.0,6.0,2.0,...,50.0,6.2,NaN,NaN,2.0,1,4207,0,0,2
285,1.0,1,5283431,38.5,66.0,24.0,1.0,1.0,1.0,1.0,...,40.0,6.7,1.0,NaN,1.0,1,31110,0,0,1
286,2.0,1,5275212,37.8,82.0,12.0,3.0,1.0,1.0,2.0,...,50.0,7.0,NaN,NaN,3.0,1,2205,0,0,2
287,2.0,9,5305129,39.5,84.0,30.0,NaN,NaN,NaN,1.0,...,28.0,5.0,NaN,NaN,1.0,2,0,0,0,2

Номер может быть любым думаю, главное, что нет пропусков. Оставляем

In [12]:
# Посчитаем выбросы пульса
q1 = df.pulse.quantile(0.25)
q3 = df.pulse.quantile(0.75)
iqr = q3 - q1
lower_bound = q1 - (1.5 * iqr) 
upper_bound = q3 + (1.5 * iqr)
remove_outliers = df[df.pulse.between(lower_bound, upper_bound, inclusive=True)].sort_values('pulse')
remove_outliers

,surgery,Age,Hospital Number,rectal temperature,pulse,respiratory rate,temperature of extremities,peripheral pulse,mucous membranes,capillary refill time,...,packed cell volume,total protein,abdominocentesis appearance,abdomcentesis total protein,outcome,surgical lesion,type of lesion1,type of lesion2,type of lesion3,cp_data
130,1.0,1,528964,37.8,30.0,12.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2.0,1,2113,0,0,2
232,1.0,1,5262543,38.5,30.0,18.0,NaN,NaN,NaN,NaN,...,40.0,7.7,NaN,NaN,1.0,1,2113,0,0,2
203,2.0,1,529685,37.2,36.0,9.0,1.0,1.0,1.0,1.0,...,35.0,5.7,NaN,NaN,1.0,2,31110,0,0,2
276,1.0,1,534787,38.0,36.0,16.0,3.0,1.0,1.0,1.0,...,37.0,75.0,2.0,1.0,3.0,2,3111,0,0,2
242,1.0,1,530354,NaN,36.0,32.0,1.0,1.0,4.0,1.0,...,41.0,5.9,NaN,NaN,2.0,1,2205,0,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
148,1.0,1,529272,38.3,132.0,NaN,NaN,3.0,6.0,2.0,...,57.0,8.0,NaN,5.2,1.0,1,2112,0,0,1
135,1.0,9,5287179,38.1,136.0,48.0,3.0,3.0,3.0,1.0,...,33.0,4.9,2.0,2.9,2.0,1,2205,0,0,1
44,1.0,1,535407,35.4,140.0,24.0,3.0,3.0,4.0,2.0,...,57.0,69.0,3.0,2.0,3.0,1,3205,0,0,2
103,1.0,9,5292489,38.0,140.0,68.0,1.0,1.0,1.0,1.0,...,39.0,5.3,NaN,NaN,1.0,1,7111,0,0,2
39,1.0,9,5277409,39.2,146.0,96.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2.0,1,2113,0,0,2

In [13]:
pd.concat([df, remove_outliers]).drop_duplicates(keep=False)

,surgery,Age,Hospital Number,rectal temperature,pulse,respiratory rate,temperature of extremities,peripheral pulse,mucous membranes,capillary refill time,...,packed cell volume,total protein,abdominocentesis appearance,abdomcentesis total protein,outcome,surgical lesion,type of lesion1,type of lesion2,type of lesion3,cp_data
3,1.0,9,5290409,39.1,164.0,84.0,4.0,1.0,6.0,2.0,...,48.0,7.2,3.0,5.3,2.0,1,2208,0,0,1
5,2.0,1,528355,NaN,NaN,NaN,2.0,1.0,3.0,1.0,...,NaN,NaN,NaN,NaN,1.0,2,0,0,0,2
28,1.0,1,5279442,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2.0,2,4300,0,0,2
41,2.0,9,5288249,39.0,150.0,72.0,NaN,NaN,NaN,NaN,...,47.0,8.5,NaN,0.1,1.0,1,9400,0,0,1
52,2.0,1,529483,NaN,NaN,NaN,1.0,1.0,3.0,1.0,...,43.0,7.7,NaN,NaN,1.0,2,3111,0,0,2
55,1.0,9,5282839,38.6,160.0,20.0,3.0,NaN,5.0,1.0,...,38.0,NaN,2.0,NaN,2.0,1,7111,0,0,1
56,1.0,1,528872,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,24.0,6.7,NaN,NaN,1.0,1,3112,0,0,2
58,1.0,1,528298,NaN,NaN,20.0,4.0,3.0,3.0,NaN,...,53.0,5.9,3.0,NaN,2.0,1,3205,0,0,1
74,1.0,9,5292929,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,37.0,4.9,NaN,NaN,2.0,1,11124,0,0,2
78,1.0,1,530693,NaN,NaN,NaN,3.0,3.0,3.0,3.0,...,46.0,5.9,NaN,NaN,2.0,1,3025,0,0,2
83,1.0,1,5279822,38.0,NaN,24.0,3.0,3.0,6.0,2.0,...,68.0,7.8,NaN,NaN,2.0,1,3205,0,0,2
93,2.0,1,530310,NaN,NaN,NaN,3.0,3.0,1.0,1.0,...,38.0,6.5,NaN,NaN,2.0,1,3205,0,0,2
115,2.0,1,533723,NaN,NaN,40.0,3.0,1.0,1.0,1.0,...,45.0,70.0,NaN,NaN,1.0,2,0,0,0,2
117,2.0,1,5290482,39.5,NaN,NaN,3.0,3.0,4.0,2.0,...,NaN,6.7,1.0,NaN,3.0,1,4205,0,0,2
126,1.0,1,530384,38.7,NaN,NaN,3.0,1.0,3.0,1.0,...,33.0,6.5,2.0,NaN,1.0,1,31110,0,0,2
136,1.0,1,530693,NaN,NaN,NaN,3.0,3.0,3.0,2.0,...,46.0,5.9,NaN,NaN,2.0,1,3025,0,0,2
151,1.0,1,529399,39.3,NaN,NaN,4.0,3.0,6.0,2.0,...,75.0,NaN,3.0,4.3,2.0,1,2207,0,0,1
159,2.0,1,528134,NaN,NaN,12.0,1.0,1.0,2.0,1.0,...,44.0,7.5,2.0,NaN,1.0,2,0,0,0,1
160,1.0,1,527916,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,35.0,58.0,2.0,1.0,1.0,1,4205,0,0,2
174,2.0,1,518476,NaN,NaN,NaN,3.0,4.0,6.0,NaN,...,NaN,NaN,NaN,NaN,2.0,1,3400,0,0,1
175,1.0,1,527929,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1.0,1,2208,0,0,2
182,1.0,1,5279822,38.0,NaN,24.0,3.0,3.0,6.0,2.0,...,68.0,7.8,NaN,NaN,2.0,1,2205,0,0,2
204,1.0,1,529528,39.2,NaN,23.0,3.0,1.0,3.0,1.0,...,36.0,6.6,1.0,3.0,1.0,1,3115,0,0,1
207,1.0,1,530297,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,45.0,8.7,NaN,NaN,2.0,1,2208,0,0,2
216,2.0,1,528977,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1.0,2,0,0,0,2
227,1.0,9,5289419,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,45.0,6.5,2.0,NaN,1.0,1,9000,0,0,1
255,1.0,9,5294539,38.8,184.0,84.0,1.0,NaN,1.0,1.0,...,33.0,3.3,NaN,NaN,2.0,1,7111,0,0,2
275,1.0,9,5297159,38.8,150.0,50.0,1.0,3.0,6.0,2.0,...,50.0,6.2,NaN,NaN,2.0,1,4207,0,0,2
288,1.0,1,529428,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1.0,1,2124,0,0,2

По пульсу видим выбросы в виде отстутствующих значений и значений выше нормы. Читаем справку:
animals with painful lesions or suffering from circulatory shock may have an elevated heart rate -  все ок, значения оставляем

In [14]:
# Посчитаем выбросы rectal temperature
q1 = df['rectal temperature'].quantile(0.25)
q3 = df['rectal temperature'].quantile(0.75)
iqr = q3 - q1
lower_bound = q1 - (1.5 * iqr) 
upper_bound = q3 + (1.5 * iqr)
remove_outliers = df[df['rectal temperature'].between(lower_bound, upper_bound, inclusive=True)].sort_values('rectal temperature')
remove_outliers

,surgery,Age,Hospital Number,rectal temperature,pulse,respiratory rate,temperature of extremities,peripheral pulse,mucous membranes,capillary refill time,...,packed cell volume,total protein,abdominocentesis appearance,abdomcentesis total protein,outcome,surgical lesion,type of lesion1,type of lesion2,type of lesion3,cp_data
113,1.0,1,527933,36.8,60.0,28.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,10.0,2.0,1,3205,0,0,1
277,2.0,1,528620,36.9,50.0,40.0,2.0,3.0,3.0,1.0,...,37.5,6.5,NaN,NaN,1.0,2,3111,0,0,2
70,2.0,1,528214,37.0,60.0,20.0,3.0,NaN,NaN,1.0,...,43.0,7.6,NaN,NaN,3.0,1,2209,0,0,1
292,1.0,1,530034,37.0,66.0,20.0,1.0,3.0,2.0,1.0,...,35.0,6.9,2.0,NaN,2.0,1,31110,0,0,2
190,1.0,1,528742,37.1,40.0,8.0,NaN,1.0,4.0,1.0,...,23.0,6.7,3.0,NaN,1.0,1,3133,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
165,1.0,1,534925,39.4,120.0,48.0,NaN,NaN,5.0,1.0,...,56.0,64.0,1.0,2.0,3.0,2,1400,0,0,2
231,2.0,1,530028,39.5,92.0,28.0,3.0,3.0,6.0,1.0,...,72.0,6.4,NaN,3.6,2.0,2,3300,0,0,2
287,2.0,9,5305129,39.5,84.0,30.0,NaN,NaN,NaN,1.0,...,28.0,5.0,NaN,NaN,1.0,2,0,0,0,2
117,2.0,1,5290482,39.5,NaN,NaN,3.0,3.0,4.0,2.0,...,NaN,6.7,1.0,NaN,3.0,1,4205,0,0,2
162,2.0,1,535176,39.5,60.0,10.0,3.0,NaN,NaN,2.0,...,38.0,56.0,1.0,NaN,1.0,2,0,0,0,2

In [15]:
pd.concat([df, remove_outliers]).drop_duplicates(keep=False).sort_values('rectal temperature').head(20)

,surgery,Age,Hospital Number,rectal temperature,pulse,respiratory rate,temperature of extremities,peripheral pulse,mucous membranes,capillary refill time,...,packed cell volume,total protein,abdominocentesis appearance,abdomcentesis total protein,outcome,surgical lesion,type of lesion1,type of lesion2,type of lesion3,cp_data
44,1.0,1,535407,35.4,140.0,24.0,3.0,3.0,4.0,2.0,...,57.0,69.0,3.0,2.0,3.0,1,3205,0,0,2
141,2.0,1,522979,36.0,42.0,30.0,NaN,NaN,5.0,1.0,...,64.0,6.8,NaN,NaN,2.0,2,1400,0,0,2
238,2.0,1,528702,36.1,88.0,NaN,3.0,3.0,3.0,1.0,...,45.0,7.0,3.0,4.8,3.0,1,2209,0,0,1
80,1.0,1,527518,36.4,98.0,35.0,3.0,3.0,4.0,1.0,...,47.0,6.4,3.0,3.6,2.0,1,2205,0,0,1
118,1.0,1,533983,36.5,78.0,30.0,1.0,NaN,1.0,1.0,...,34.0,75.0,2.0,1.0,1.0,1,3112,6112,0,2
298,1.0,1,530612,36.5,100.0,24.0,3.0,3.0,3.0,1.0,...,50.0,6.0,3.0,3.4,1.0,1,2208,0,0,1
251,2.0,1,527940,36.6,42.0,18.0,3.0,3.0,2.0,1.0,...,52.0,7.1,NaN,NaN,2.0,1,5111,0,0,2
99,2.0,1,530002,39.6,108.0,51.0,3.0,3.0,6.0,2.0,...,59.0,8.0,2.0,2.6,1.0,2,4300,0,0,1
75,1.0,9,534092,39.7,100.0,NaN,3.0,3.0,5.0,2.0,...,48.0,57.0,2.0,2.0,3.0,1,1400,0,0,2
20,1.0,1,530157,39.9,72.0,60.0,1.0,1.0,5.0,2.0,...,46.0,6.1,2.0,NaN,1.0,1,2111,0,0,2
281,2.0,1,530624,40.0,78.0,NaN,3.0,3.0,5.0,1.0,...,66.0,6.5,NaN,NaN,2.0,1,8400,0,0,1
54,2.0,1,529461,40.3,114.0,36.0,3.0,3.0,1.0,2.0,...,57.0,8.1,3.0,4.5,3.0,1,7400,0,0,1
91,2.0,1,529461,40.3,114.0,36.0,3.0,3.0,1.0,2.0,...,57.0,8.1,3.0,4.5,2.0,1,3205,0,0,1
259,1.0,1,527734,40.8,72.0,42.0,3.0,3.0,1.0,1.0,...,54.0,7.4,3.0,NaN,2.0,1,11400,0,0,1
5,2.0,1,528355,NaN,NaN,NaN,2.0,1.0,3.0,1.0,...,NaN,NaN,NaN,NaN,1.0,2,0,0,0,2
7,1.0,1,529607,NaN,60.0,NaN,3.0,NaN,NaN,1.0,...,44.0,8.3,NaN,NaN,2.0,1,2208,0,0,2
8,2.0,1,530051,NaN,80.0,36.0,3.0,4.0,3.0,1.0,...,38.0,6.2,NaN,NaN,3.0,1,3205,0,0,2
16,1.0,9,5301219,NaN,128.0,36.0,3.0,3.0,4.0,2.0,...,53.0,7.8,3.0,4.7,2.0,2,1400,0,0,1
28,1.0,1,5279442,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2.0,2,4300,0,0,2
34,1.0,1,529796,NaN,100.0,30.0,3.0,3.0,4.0,2.0,...,52.0,6.6,NaN,NaN,1.0,1,1124,0,0,2

Температура может быть повышенной, оставляем

In [28]:
# Посчитаем выбросы mucous membranes
q1 = df['mucous membranes'].quantile(0.25)
q3 = df['mucous membranes'].quantile(0.75)
iqr = q3 - q1
lower_bound = q1 - (1.5 * iqr) 
upper_bound = q3 + (1.5 * iqr)
remove_outliers = df[df['mucous membranes'].between(lower_bound, upper_bound, inclusive=True)].sort_values('mucous membranes')
remove_outliers

,surgery,Age,Hospital Number,rectal temperature,pulse,respiratory rate,temperature of extremities,peripheral pulse,mucous membranes,capillary refill time,...,packed cell volume,total protein,abdominocentesis appearance,abdomcentesis total protein,outcome,surgical lesion,type of lesion1,type of lesion2,type of lesion3,cp_data
225,2.0,1,528931,38.4,54.0,24.0,1.0,1.0,1.0,1.0,...,49.0,7.2,1.0,8.0,1.0,2,3111,0,0,1
203,2.0,1,529685,37.2,36.0,9.0,1.0,1.0,1.0,1.0,...,35.0,5.7,NaN,NaN,1.0,2,31110,0,0,2
103,1.0,9,5292489,38.0,140.0,68.0,1.0,1.0,1.0,1.0,...,39.0,5.3,NaN,NaN,1.0,1,7111,0,0,2
102,2.0,1,534938,38.3,40.0,16.0,3.0,NaN,1.0,1.0,...,37.0,57.0,NaN,NaN,1.0,2,0,0,0,2
100,1.0,1,535364,38.2,40.0,16.0,3.0,3.0,1.0,1.0,...,34.0,66.0,NaN,NaN,1.0,2,0,0,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99,2.0,1,530002,39.6,108.0,51.0,3.0,3.0,6.0,2.0,...,59.0,8.0,2.0,2.6,1.0,2,4300,0,0,1
79,1.0,1,527463,37.5,96.0,18.0,1.0,3.0,6.0,2.0,...,69.0,8.9,3.0,NaN,1.0,1,2208,0,0,1
228,1.0,1,535196,37.3,90.0,40.0,3.0,NaN,6.0,2.0,...,65.0,50.0,3.0,2.0,3.0,1,3205,0,0,2
142,1.0,1,530402,NaN,120.0,NaN,4.0,3.0,6.0,2.0,...,57.0,4.5,3.0,3.9,2.0,1,3205,0,0,1
231,2.0,1,530028,39.5,92.0,28.0,3.0,3.0,6.0,1.0,...,72.0,6.4,NaN,3.6,2.0,2,3300,0,0,2

In [29]:
pd.concat([df, remove_outliers]).drop_duplicates(keep=False).sort_values('mucous membranes')

,surgery,Age,Hospital Number,rectal temperature,pulse,respiratory rate,temperature of extremities,peripheral pulse,mucous membranes,capillary refill time,...,packed cell volume,total protein,abdominocentesis appearance,abdomcentesis total protein,outcome,surgical lesion,type of lesion1,type of lesion2,type of lesion3,cp_data
0,2.0,1,530101,38.5,66.0,28.0,3.0,3.0,NaN,2.0,...,45.0,8.4,NaN,NaN,2.0,2,11300,0,0,2
7,1.0,1,529607,NaN,60.0,NaN,3.0,NaN,NaN,1.0,...,44.0,8.3,NaN,NaN,2.0,1,2208,0,0,2
17,2.0,1,526639,37.5,48.0,24.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1.0,2,0,0,0,2
23,1.0,9,534998,38.3,130.0,60.0,NaN,3.0,NaN,1.0,...,50.0,70.0,NaN,NaN,1.0,1,3111,0,0,2
25,2.0,1,529518,37.8,60.0,42.0,NaN,NaN,NaN,1.0,...,NaN,NaN,NaN,NaN,1.0,2,0,0,0,2
28,1.0,1,5279442,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2.0,2,4300,0,0,2
37,1.0,1,533847,37.8,72.0,NaN,NaN,3.0,NaN,1.0,...,56.0,80.0,1.0,2.0,1.0,1,3111,0,0,2
39,1.0,9,5277409,39.2,146.0,96.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2.0,1,2113,0,0,2
41,2.0,9,5288249,39.0,150.0,72.0,NaN,NaN,NaN,NaN,...,47.0,8.5,NaN,0.1,1.0,1,9400,0,0,1
53,2.0,1,530544,38.6,40.0,20.0,NaN,NaN,NaN,1.0,...,41.0,6.4,NaN,NaN,1.0,2,3111,0,0,1
56,1.0,1,528872,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,24.0,6.7,NaN,NaN,1.0,1,3112,0,0,2
70,2.0,1,528214,37.0,60.0,20.0,3.0,NaN,NaN,1.0,...,43.0,7.6,NaN,NaN,3.0,1,2209,0,0,1
72,1.0,1,5299253,37.7,56.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2.0,1,2113,0,0,2
74,1.0,9,5292929,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,37.0,4.9,NaN,NaN,2.0,1,11124,0,0,2
87,2.0,1,528006,NaN,40.0,16.0,NaN,NaN,NaN,1.0,...,50.0,7.0,2.0,3.9,3.0,1,2208,0,0,1
90,2.0,1,534197,38.0,52.0,16.0,NaN,NaN,NaN,NaN,...,53.0,86.0,NaN,NaN,1.0,1,2322,0,0,2
111,1.0,1,533736,38.3,40.0,16.0,3.0,NaN,NaN,1.0,...,38.0,58.0,1.0,2.0,1.0,1,3111,7111,0,2
113,1.0,1,527933,36.8,60.0,28.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,10.0,2.0,1,3205,0,0,1
127,1.0,1,5262541,37.4,50.0,32.0,3.0,3.0,NaN,1.0,...,45.0,7.9,2.0,1.0,1.0,1,2208,0,0,1
130,1.0,1,528964,37.8,30.0,12.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2.0,1,2113,0,0,2
139,2.0,1,534491,38.0,60.0,32.0,1.0,1.0,NaN,1.0,...,50.0,7.0,1.0,1.0,1.0,2,0,0,0,2
149,2.0,1,535314,38.7,48.0,24.0,NaN,NaN,NaN,NaN,...,34.0,63.0,NaN,NaN,1.0,2,0,0,0,2
160,1.0,1,527916,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,35.0,58.0,2.0,1.0,1.0,1,4205,0,0,2
161,1.0,1,530431,38.3,42.0,24.0,NaN,NaN,NaN,1.0,...,40.0,8.5,NaN,NaN,2.0,1,7113,0,0,2
162,2.0,1,535176,39.5,60.0,10.0,3.0,NaN,NaN,2.0,...,38.0,56.0,1.0,NaN,1.0,2,0,0,0,2
169,1.0,1,535085,NaN,65.0,24.0,NaN,NaN,NaN,2.0,...,NaN,NaN,NaN,NaN,3.0,1,3205,0,0,2
175,1.0,1,527929,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1.0,1,2208,0,0,2
188,1.0,1,533887,38.5,60.0,NaN,1.0,1.0,NaN,1.0,...,33.0,53.0,1.0,NaN,1.0,1,4111,0,0,2
197,2.0,1,521399,38.5,96.0,36.0,3.0,3.0,NaN,2.0,...,70.0,8.5,NaN,NaN,2.0,1,1400,0,0,1
202,1.0,1,534073,37.5,48.0,40.0,NaN,NaN,NaN,NaN,...,41.0,55.0,3.0,2.0,3.0,1,2208,0,0,2
207,1.0,1,530297,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,45.0,8.7,NaN,NaN,2.0,1,2208,0,0,2
216,2.0,1,528977,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1.0,2,0,0,0,2
217,1.0,1,5279441,38.0,76.0,18.0,NaN,NaN,NaN,2.0,...,71.0,11.0,NaN,NaN,1.0,1,2209,0,0,1
220,1.0,1,535029,39.2,88.0,58.0,4.0,4.0,NaN,2.0,...,NaN,NaN,2.0,2.0,3.0,2,3205,0,0,2
221,1.0,1,535031,38.5,92.0,40.0,4.0,3.0,NaN,1.0,...,46.0,67.0,2.0,2.0,1.0,1,2208,0,0,2
227,1.0,9,5289419,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,45.0,6.5,2.0,NaN,1.0,1,9000,0,0,1
229,1.0,9,534597,38.5,120.0,70.0,NaN,NaN,NaN,NaN,...,35.0,54.0,1.0,1.0,1.0,1,4205,3111,2209,2
230,1.0,1,534280,38.5,104.0,40.0,3.0,3.0,NaN,1.0,...,NaN,NaN,NaN,NaN,1.0,1,2124,0,0,2
232,1.0,1,5262543,38.5,30.0,18.0,NaN,NaN,NaN,NaN,...,40.0,7.7,NaN,NaN,1.0,1,2113,0,0,2
239,1.0,1,534183,38.1,70.0,22.0,NaN,1.0,NaN,1.0,...,36.0,65.0,NaN,NaN,3.0,1,3205,0,0,2
243,1.0,1,5281091,38.4,92.0,20.0,1.0,NaN,NaN,2.0,...,NaN,NaN,NaN,NaN,1.0,1,2208,0,0,1
262,2.0,9,5305629,38.6,88.0,28.0,NaN,NaN,NaN,NaN,...,35.0,5.9,NaN,NaN,1.0,2,0,0,0,2
274,1.0,1,534624,NaN,76.0,NaN,NaN,3.0,NaN,NaN,...,NaN,NaN,NaN,NaN,3.0,1,11124,0,0,2
283,1.0,1,527758,38.2,72.0,18.0,NaN,NaN,NaN,NaN,...,35.0,6.4,NaN,NaN,1.0,1,3124,0,0,2
287,2.0,9,5305129,39.5,84.0,30.0,NaN,NaN,NaN,1.0,...,28.0,5.0,NaN,NaN,1.0,2,0,0,0,2
288,1.0,1,529428,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1.0,1,2124,0,0,2
299,1.0,1,534618,37.2,40.0,20.0,NaN,NaN,NaN,NaN,...,36.0,62.0,1.0,1.0,3.0,2,6112,0,0,2

Найдены только пустые значения, все ок

In [30]:
# Посчитаем выбросы total protein
q1 = df['total protein'].quantile(0.25)
q3 = df['total protein'].quantile(0.75)
iqr = q3 - q1
lower_bound = q1 - (1.5 * iqr) 
upper_bound = q3 + (1.5 * iqr)
remove_outliers = df[df['total protein'].between(lower_bound, upper_bound, inclusive=True)].sort_values('total protein')
remove_outliers.tail(30)

,surgery,Age,Hospital Number,rectal temperature,pulse,respiratory rate,temperature of extremities,peripheral pulse,mucous membranes,capillary refill time,...,packed cell volume,total protein,abdominocentesis appearance,abdomcentesis total protein,outcome,surgical lesion,type of lesion1,type of lesion2,type of lesion3,cp_data
76,1.0,1,534615,37.600000,38.0,20.0,3.0,3.0,1.0,1.0,...,37.0,68.0,NaN,NaN,1.0,1,3205,0,0,2
183,2.0,1,534857,37.800000,56.0,16.0,1.0,1.0,2.0,1.0,...,44.0,68.0,1.0,1.0,1.0,2,0,0,0,2
260,2.0,1,534933,38.000000,40.0,25.0,NaN,1.0,1.0,1.0,...,37.0,69.0,NaN,NaN,1.0,2,0,0,0,2
44,1.0,1,535407,35.400000,140.0,24.0,3.0,3.0,4.0,2.0,...,57.0,69.0,3.0,2.0,3.0,1,3205,0,0,2
95,1.0,1,535158,37.300000,48.0,20.0,NaN,1.0,2.0,1.0,...,41.0,69.0,NaN,NaN,1.0,1,3205,0,0,2
23,1.0,9,534998,38.300000,130.0,60.0,NaN,3.0,4.0,1.0,...,50.0,70.0,NaN,NaN,1.0,1,3111,0,0,2
178,1.0,1,533968,38.167917,60.0,30.0,3.0,3.0,4.0,2.0,...,45.0,70.0,3.0,2.0,1.0,1,6111,3111,0,2
254,1.0,1,533738,38.167917,80.0,NaN,3.0,3.0,3.0,1.0,...,43.0,70.0,NaN,NaN,1.0,1,3111,0,0,2
115,2.0,1,533723,38.167917,NaN,40.0,3.0,1.0,1.0,1.0,...,45.0,70.0,NaN,NaN,1.0,2,0,0,0,2
119,2.0,1,535166,38.100000,56.0,20.0,2.0,1.0,2.0,1.0,...,46.0,70.0,NaN,NaN,1.0,2,0,0,0,2
146,1.0,1,534115,38.200000,48.0,NaN,1.0,3.0,3.0,1.0,...,42.0,71.0,NaN,NaN,1.0,1,3111,0,0,2
138,2.0,1,532349,38.000000,56.0,NaN,1.0,2.0,3.0,1.0,...,42.0,71.0,NaN,NaN,1.0,2,0,0,0,2
65,1.0,1,534885,38.167917,60.0,36.0,3.0,1.0,3.0,1.0,...,26.0,72.0,2.0,1.0,1.0,1,2208,0,0,2
132,NaN,1,534572,38.000000,48.0,20.0,3.0,1.0,3.0,1.0,...,43.0,73.0,2.0,1.0,NaN,1,3111,0,0,2
66,2.0,1,534784,37.900000,72.0,NaN,1.0,1.0,5.0,2.0,...,58.0,74.0,1.0,2.0,1.0,1,2322,0,0,2
192,1.0,1,534788,38.200000,48.0,18.0,1.0,1.0,1.0,1.0,...,48.0,74.0,1.0,2.0,1.0,1,5111,0,0,2
276,1.0,1,534787,38.000000,36.0,16.0,3.0,1.0,1.0,1.0,...,37.0,75.0,2.0,1.0,3.0,2,3111,0,0,2
157,1.0,1,533928,37.800000,60.0,24.0,1.0,NaN,3.0,2.0,...,52.0,75.0,NaN,NaN,3.0,1,2205,0,0,2
118,1.0,1,533983,36.500000,78.0,30.0,1.0,NaN,1.0,1.0,...,34.0,75.0,2.0,1.0,1.0,1,3112,6112,0,2
29,2.0,1,535415,37.700000,48.0,NaN,2.0,1.0,1.0,1.0,...,45.0,76.0,NaN,NaN,1.0,2,0,0,0,2
114,1.0,1,532349,38.400000,44.0,24.0,3.0,NaN,4.0,NaN,...,50.0,77.0,NaN,NaN,1.0,1,3205,0,0,2
77,2.0,1,534753,38.700000,52.0,20.0,2.0,NaN,1.0,1.0,...,33.0,77.0,NaN,NaN,1.0,2,0,0,0,2
37,1.0,1,533847,37.800000,72.0,NaN,NaN,3.0,3.0,1.0,...,56.0,80.0,1.0,2.0,1.0,1,3111,0,0,2
145,2.0,1,535246,38.167917,80.0,32.0,3.0,3.0,2.0,1.0,...,50.0,80.0,NaN,NaN,1.0,1,0,0,0,2
14,1.0,1,534917,38.200000,76.0,28.0,3.0,1.0,1.0,1.0,...,46.0,81.0,1.0,2.0,1.0,1,2112,0,0,2
144,1.0,1,534519,37.100000,84.0,40.0,3.0,3.0,6.0,1.0,...,75.0,81.0,NaN,NaN,3.0,2,1400,0,0,2
63,2.0,1,534293,38.200000,130.0,16.0,4.0,3.0,4.0,2.0,...,65.0,82.0,2.0,2.0,3.0,2,2209,1400,0,2
1,1.0,1,534817,39.200000,88.0,20.0,NaN,NaN,4.0,1.0,...,50.0,85.0,2.0,2.0,3.0,2,2208,0,0,2
90,2.0,1,534197,38.000000,52.0,16.0,NaN,NaN,NaN,NaN,...,53.0,86.0,NaN,NaN,1.0,1,2322,0,0,2
208,1.0,1,535338,37.800000,88.0,80.0,3.0,3.0,5.0,2.0,...,64.0,89.0,NaN,NaN,3.0,1,3205,0,0,2

In [31]:
pd.concat([df, remove_outliers]).drop_duplicates(keep=False).sort_values('total protein')

,surgery,Age,Hospital Number,rectal temperature,pulse,respiratory rate,temperature of extremities,peripheral pulse,mucous membranes,capillary refill time,...,packed cell volume,total protein,abdominocentesis appearance,abdomcentesis total protein,outcome,surgical lesion,type of lesion1,type of lesion2,type of lesion3,cp_data
5,2.0,1,528355,NaN,NaN,NaN,2.0,1.0,3.0,1.0,...,NaN,NaN,NaN,NaN,1.0,2,0,0,0,2
17,2.0,1,526639,37.5,48.0,24.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1.0,2,0,0,0,2
25,2.0,1,529518,37.8,60.0,42.0,NaN,NaN,NaN,1.0,...,NaN,NaN,NaN,NaN,1.0,2,0,0,0,2
28,1.0,1,5279442,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2.0,2,4300,0,0,2
39,1.0,9,5277409,39.2,146.0,96.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2.0,1,2113,0,0,2
51,1.0,1,527706,37.4,84.0,36.0,1.0,NaN,3.0,2.0,...,NaN,NaN,3.0,NaN,2.0,1,7209,0,0,1
55,1.0,9,5282839,38.6,160.0,20.0,3.0,NaN,5.0,1.0,...,38.0,NaN,2.0,NaN,2.0,1,7111,0,0,1
59,2.0,1,528904,NaN,96.0,NaN,3.0,3.0,3.0,2.0,...,60.0,NaN,NaN,NaN,2.0,1,4205,0,0,2
72,1.0,1,5299253,37.7,56.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2.0,1,2113,0,0,2
81,1.0,1,534756,37.3,40.0,NaN,NaN,3.0,1.0,1.0,...,36.0,NaN,3.0,2.0,1.0,1,3111,0,0,2
101,1.0,1,534899,NaN,60.0,20.0,4.0,3.0,4.0,2.0,...,NaN,NaN,NaN,NaN,3.0,1,3205,0,0,2
113,1.0,1,527933,36.8,60.0,28.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,10.0,2.0,1,3205,0,0,1
130,1.0,1,528964,37.8,30.0,12.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2.0,1,2113,0,0,2
137,1.0,1,534324,38.0,48.0,NaN,1.0,1.0,1.0,1.0,...,NaN,NaN,NaN,NaN,1.0,1,3111,0,0,2
151,1.0,1,529399,39.3,NaN,NaN,4.0,3.0,6.0,2.0,...,75.0,NaN,3.0,4.3,2.0,1,2207,0,0,1
158,2.0,1,528248,38.0,42.0,40.0,3.0,1.0,1.0,1.0,...,NaN,NaN,NaN,NaN,1.0,2,3111,0,0,2
169,1.0,1,535085,NaN,65.0,24.0,NaN,NaN,NaN,2.0,...,NaN,NaN,NaN,NaN,3.0,1,3205,0,0,2
174,2.0,1,518476,NaN,NaN,NaN,3.0,4.0,6.0,NaN,...,NaN,NaN,NaN,NaN,2.0,1,3400,0,0,1
175,1.0,1,527929,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1.0,1,2208,0,0,2
177,1.0,1,523190,NaN,68.0,14.0,NaN,NaN,4.0,1.0,...,NaN,NaN,2.0,2.8,2.0,1,4205,0,0,1
179,2.0,1,528151,38.5,100.0,NaN,3.0,3.0,5.0,2.0,...,NaN,NaN,NaN,NaN,3.0,2,1111,0,0,1
185,1.0,1,534833,38.5,120.0,60.0,4.0,3.0,6.0,2.0,...,54.0,NaN,NaN,NaN,1.0,1,5400,0,0,2
205,2.0,1,528151,38.5,100.0,NaN,3.0,3.0,5.0,2.0,...,NaN,NaN,NaN,NaN,3.0,2,4124,0,0,2
216,2.0,1,528977,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1.0,2,0,0,0,2
218,1.0,1,535240,38.1,40.0,36.0,1.0,2.0,2.0,1.0,...,NaN,NaN,NaN,NaN,3.0,1,3112,0,0,2
220,1.0,1,535029,39.2,88.0,58.0,4.0,4.0,NaN,2.0,...,NaN,NaN,2.0,2.0,3.0,2,3205,0,0,2
230,1.0,1,534280,38.5,104.0,40.0,3.0,3.0,NaN,1.0,...,NaN,NaN,NaN,NaN,1.0,1,2124,0,0,2
243,1.0,1,5281091,38.4,92.0,20.0,1.0,NaN,NaN,2.0,...,NaN,NaN,NaN,NaN,1.0,1,2208,0,0,1
245,2.0,1,528904,NaN,96.0,NaN,3.0,3.0,3.0,2.0,...,60.0,NaN,NaN,NaN,2.0,1,41110,0,0,2
248,1.0,1,527709,38.0,108.0,60.0,2.0,3.0,4.0,1.0,...,NaN,NaN,3.0,NaN,1.0,1,2205,0,0,2
274,1.0,1,534624,NaN,76.0,NaN,NaN,3.0,NaN,NaN,...,NaN,NaN,NaN,NaN,3.0,1,11124,0,0,2
288,1.0,1,529428,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1.0,1,2124,0,0,2
296,2.0,1,527702,37.2,72.0,24.0,3.0,2.0,4.0,2.0,...,44.0,NaN,3.0,3.3,3.0,1,2208,0,0,1

Найдены только пустые значения, все ок

In [33]:
# Посчитаем выбросы abdominocentesis appearance
q1 = df['abdominocentesis appearance'].quantile(0.25)
q3 = df['abdominocentesis appearance'].quantile(0.75)
iqr = q3 - q1
lower_bound = q1 - (1.5 * iqr) 
upper_bound = q3 + (1.5 * iqr)
remove_outliers = df[df['abdominocentesis appearance'].between(lower_bound, upper_bound, inclusive=True)].sort_values('abdominocentesis appearance')
remove_outliers

,surgery,Age,Hospital Number,rectal temperature,pulse,respiratory rate,temperature of extremities,peripheral pulse,mucous membranes,capillary refill time,...,packed cell volume,total protein,abdominocentesis appearance,abdomcentesis total protein,outcome,surgical lesion,type of lesion1,type of lesion2,type of lesion3,cp_data
156,2.0,1,528996,38.6,52.0,20.0,1.0,1.0,1.0,1.0,...,36.0,6.6,1.0,5.0,1.0,2,0,0,0,1
111,1.0,1,533736,38.3,40.0,16.0,3.0,NaN,NaN,1.0,...,38.0,58.0,1.0,2.0,1.0,1,3111,7111,0,2
117,2.0,1,5290482,39.5,NaN,NaN,3.0,3.0,4.0,2.0,...,NaN,6.7,1.0,NaN,3.0,1,4205,0,0,2
122,2.0,1,534579,38.7,40.0,28.0,2.0,1.0,1.0,1.0,...,39.0,62.0,1.0,1.0,1.0,2,0,0,0,2
123,1.0,1,530360,38.2,64.0,24.0,1.0,1.0,3.0,1.0,...,45.0,7.5,1.0,2.0,2.0,1,3205,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
226,1.0,1,528503,39.2,120.0,20.0,4.0,3.0,5.0,2.0,...,60.0,8.8,3.0,NaN,2.0,1,2205,0,0,2
64,1.0,1,529667,39.0,64.0,36.0,3.0,1.0,4.0,2.0,...,44.0,7.5,3.0,5.0,1.0,1,2113,0,0,1
228,1.0,1,535196,37.3,90.0,40.0,3.0,NaN,6.0,2.0,...,65.0,50.0,3.0,2.0,3.0,1,3205,0,0,2
237,2.0,1,533750,37.9,54.0,42.0,2.0,1.0,5.0,1.0,...,47.0,54.0,3.0,1.0,1.0,2,0,0,0,2
40,1.0,1,529498,NaN,88.0,NaN,3.0,3.0,6.0,2.0,...,63.0,6.5,3.0,NaN,2.0,1,4205,0,0,2

In [34]:
pd.concat([df, remove_outliers]).drop_duplicates(keep=False).sort_values('abdominocentesis appearance')

,surgery,Age,Hospital Number,rectal temperature,pulse,respiratory rate,temperature of extremities,peripheral pulse,mucous membranes,capillary refill time,...,packed cell volume,total protein,abdominocentesis appearance,abdomcentesis total protein,outcome,surgical lesion,type of lesion1,type of lesion2,type of lesion3,cp_data
0,2.0,1,530101,38.5,66.0,28.0,3.0,3.0,NaN,2.0,...,45.0,8.4,NaN,NaN,2.0,2,11300,0,0,2
2,2.0,1,530334,38.3,40.0,24.0,1.0,1.0,3.0,1.0,...,33.0,6.7,NaN,NaN,1.0,2,0,0,0,1
4,2.0,1,530255,37.3,104.0,35.0,NaN,NaN,6.0,2.0,...,74.0,7.4,NaN,NaN,2.0,2,4300,0,0,2
5,2.0,1,528355,NaN,NaN,NaN,2.0,1.0,3.0,1.0,...,NaN,NaN,NaN,NaN,1.0,2,0,0,0,2
6,1.0,1,526802,37.9,48.0,16.0,1.0,1.0,1.0,1.0,...,37.0,7.0,NaN,NaN,1.0,1,3124,0,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
290,2.0,1,535054,38.6,45.0,16.0,2.0,1.0,2.0,1.0,...,43.0,58.0,NaN,NaN,1.0,2,0,0,0,2
293,1.0,1,534004,NaN,78.0,24.0,3.0,3.0,3.0,1.0,...,43.0,62.0,NaN,2.0,3.0,2,2209,0,0,2
294,2.0,1,533902,38.5,40.0,16.0,1.0,1.0,1.0,1.0,...,37.0,67.0,NaN,NaN,1.0,2,0,0,0,2
295,1.0,1,533886,NaN,120.0,70.0,4.0,NaN,4.0,2.0,...,55.0,65.0,NaN,NaN,3.0,2,3205,0,0,2
297,1.0,1,529386,37.5,72.0,30.0,4.0,3.0,4.0,1.0,...,60.0,6.8,NaN,NaN,2.0,1,3205,0,0,2

Найдены только пустые значения, все ок

In [36]:
# Посчитаем выбросы abdominocentesis appearance
q1 = df['capillary refill time'].quantile(0.25)
q3 = df['capillary refill time'].quantile(0.75)
iqr = q3 - q1
lower_bound = q1 - (1.5 * iqr) 
upper_bound = q3 + (1.5 * iqr)
remove_outliers = df[df['capillary refill time'].between(lower_bound, upper_bound, inclusive=True)].sort_values('capillary refill time')
remove_outliers

,surgery,Age,Hospital Number,rectal temperature,pulse,respiratory rate,temperature of extremities,peripheral pulse,mucous membranes,capillary refill time,...,packed cell volume,total protein,abdominocentesis appearance,abdomcentesis total protein,outcome,surgical lesion,type of lesion1,type of lesion2,type of lesion3,cp_data
147,2.0,1,530001,38.0,44.0,12.0,2.0,1.0,3.0,1.0,...,33.0,6.5,NaN,NaN,2.0,1,2209,0,0,2
170,2.0,1,532985,37.5,44.0,20.0,1.0,1.0,3.0,1.0,...,35.0,7.2,NaN,NaN,1.0,2,0,0,0,2
172,1.0,1,535292,38.5,129.0,48.0,3.0,3.0,3.0,1.0,...,57.0,66.0,3.0,2.0,1.0,1,2206,0,0,2
176,1.0,1,535130,38.2,60.0,30.0,1.0,1.0,3.0,1.0,...,48.0,66.0,NaN,NaN,1.0,1,6112,0,0,2
177,1.0,1,523190,NaN,68.0,14.0,NaN,NaN,4.0,1.0,...,NaN,NaN,2.0,2.8,2.0,1,4205,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
83,1.0,1,5279822,38.0,NaN,24.0,3.0,3.0,6.0,2.0,...,68.0,7.8,NaN,NaN,2.0,1,3205,0,0,2
84,1.0,1,529849,37.8,60.0,80.0,1.0,3.0,2.0,2.0,...,40.0,4.5,2.0,NaN,1.0,1,5206,0,0,1
0,2.0,1,530101,38.5,66.0,28.0,3.0,3.0,NaN,2.0,...,45.0,8.4,NaN,NaN,2.0,2,11300,0,0,2
78,1.0,1,530693,NaN,NaN,NaN,3.0,3.0,3.0,3.0,...,46.0,5.9,NaN,NaN,2.0,1,3025,0,0,2
85,2.0,1,529304,38.0,54.0,30.0,2.0,3.0,3.0,3.0,...,45.0,6.2,NaN,NaN,1.0,2,400,0,0,2

In [37]:
pd.concat([df, remove_outliers]).drop_duplicates(keep=False).sort_values('capillary refill time')

,surgery,Age,Hospital Number,rectal temperature,pulse,respiratory rate,temperature of extremities,peripheral pulse,mucous membranes,capillary refill time,...,packed cell volume,total protein,abdominocentesis appearance,abdomcentesis total protein,outcome,surgical lesion,type of lesion1,type of lesion2,type of lesion3,cp_data
17,2.0,1,526639,37.5,48.0,24.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1.0,2,0,0,0,2
19,2.0,1,532110,39.4,110.0,35.0,4.0,3.0,6.0,NaN,...,55.0,8.7,NaN,NaN,1.0,2,0,0,0,2
22,1.0,1,521681,38.6,42.0,34.0,2.0,1.0,4.0,NaN,...,48.0,7.2,NaN,NaN,1.0,1,3111,0,0,2
28,1.0,1,5279442,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2.0,2,4300,0,0,2
39,1.0,9,5277409,39.2,146.0,96.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2.0,1,2113,0,0,2
41,2.0,9,5288249,39.0,150.0,72.0,NaN,NaN,NaN,NaN,...,47.0,8.5,NaN,0.1,1.0,1,9400,0,0,1
56,1.0,1,528872,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,24.0,6.7,NaN,NaN,1.0,1,3112,0,0,2
58,1.0,1,528298,NaN,NaN,20.0,4.0,3.0,3.0,NaN,...,53.0,5.9,3.0,NaN,2.0,1,3205,0,0,1
72,1.0,1,5299253,37.7,56.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2.0,1,2113,0,0,2
74,1.0,9,5292929,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,37.0,4.9,NaN,NaN,2.0,1,11124,0,0,2
90,2.0,1,534197,38.0,52.0,16.0,NaN,NaN,NaN,NaN,...,53.0,86.0,NaN,NaN,1.0,1,2322,0,0,2
113,1.0,1,527933,36.8,60.0,28.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,10.0,2.0,1,3205,0,0,1
114,1.0,1,532349,38.4,44.0,24.0,3.0,NaN,4.0,NaN,...,50.0,77.0,NaN,NaN,1.0,1,3205,0,0,2
130,1.0,1,528964,37.8,30.0,12.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2.0,1,2113,0,0,2
149,2.0,1,535314,38.7,48.0,24.0,NaN,NaN,NaN,NaN,...,34.0,63.0,NaN,NaN,1.0,2,0,0,0,2
160,1.0,1,527916,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,35.0,58.0,2.0,1.0,1.0,1,4205,0,0,2
171,2.0,1,527677,39.0,86.0,16.0,3.0,3.0,5.0,NaN,...,68.0,5.8,3.0,6.0,2.0,1,5400,0,0,1
174,2.0,1,518476,NaN,NaN,NaN,3.0,4.0,6.0,NaN,...,NaN,NaN,NaN,NaN,2.0,1,3400,0,0,1
175,1.0,1,527929,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1.0,1,2208,0,0,2
195,2.0,1,533697,38.0,44.0,12.0,3.0,1.0,1.0,NaN,...,42.0,64.0,NaN,NaN,1.0,2,0,0,0,2
202,1.0,1,534073,37.5,48.0,40.0,NaN,NaN,NaN,NaN,...,41.0,55.0,3.0,2.0,3.0,1,2208,0,0,2
207,1.0,1,530297,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,45.0,8.7,NaN,NaN,2.0,1,2208,0,0,2
216,2.0,1,528977,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1.0,2,0,0,0,2
227,1.0,9,5289419,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,45.0,6.5,2.0,NaN,1.0,1,9000,0,0,1
229,1.0,9,534597,38.5,120.0,70.0,NaN,NaN,NaN,NaN,...,35.0,54.0,1.0,1.0,1.0,1,4205,3111,2209,2
232,1.0,1,5262543,38.5,30.0,18.0,NaN,NaN,NaN,NaN,...,40.0,7.7,NaN,NaN,1.0,1,2113,0,0,2
262,2.0,9,5305629,38.6,88.0,28.0,NaN,NaN,NaN,NaN,...,35.0,5.9,NaN,NaN,1.0,2,0,0,0,2
274,1.0,1,534624,NaN,76.0,NaN,NaN,3.0,NaN,NaN,...,NaN,NaN,NaN,NaN,3.0,1,11124,0,0,2
280,1.0,1,534644,38.6,48.0,12.0,NaN,NaN,1.0,NaN,...,36.0,67.0,NaN,NaN,1.0,2,0,0,0,2
283,1.0,1,527758,38.2,72.0,18.0,NaN,NaN,NaN,NaN,...,35.0,6.4,NaN,NaN,1.0,1,3124,0,0,2
288,1.0,1,529428,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,1.0,1,2124,0,0,2
299,1.0,1,534618,37.2,40.0,20.0,NaN,NaN,NaN,NaN,...,36.0,62.0,1.0,1.0,3.0,2,6112,0,0,2

Найдены только пустые значения, все ок

# Задание 3

In [6]:
for col in df.columns:
    pct_missing = df[col].isnull().mean()
    print(f'{col} - {pct_missing :.1%}')

surgery - 0.3%
Age - 0.0%
Hospital Number - 0.0%
rectal temperature - 20.0%
pulse - 8.0%
respiratory rate - 19.3%
temperature of extremities - 18.7%
peripheral pulse - 23.0%
mucous membranes - 15.7%
capillary refill time - 10.7%
pain - 18.3%
peristalsis - 14.7%
abdominal distension - 18.7%
nasogastric tube - 34.7%
nasogastric reflux - 35.3%
nasogastric reflux PH - 82.3%
rectal examination - 34.0%
abdomen - 39.3%
packed cell volume - 9.7%
total protein - 11.0%
abdominocentesis appearance - 55.0%
abdomcentesis total protein - 66.0%
outcome - 0.3%
surgical lesion - 0.0%
type of lesion1 - 0.0%
type of lesion2 - 0.0%
type of lesion3 - 0.0%
cp_data - 0.0%

In [7]:
# surgery - логично было бы заполнить на основе столбца с хирургическим вмешательством

df.surgery.fillna(df.groupby('surgical lesion').surgery.transform('median'), inplace=True)

In [8]:
# rectal temperature - мне кажется здесь будет верней рассчитать среднюю температуру
# каждая лошадь индивидуальна и четкой зависимсти температуры от чего-либо в конкретный момент времени мы не знаем

df['rectal temperature'].fillna(df['rectal temperature'].mean(), inplace=True)

mucous membranes, capillary refill time - закономерностей не нашел, так как это категорийный вид, то можно не заполнять.

total protein, pulse  - индивидуальный дискретный параметр. Я бы поставил среднее значение или на основе двух и более групп, посоветовавшись со специалистом по лошадям

In [9]:
df['total protein'].fillna(df['total protein'].mean(), inplace=True)
df.pulse.fillna(df.pulse.mean(), inplace=True)

# или пример с заменой по столбцам

df['total protein'].fillna(df.groupby(['pulse', 'peripheral pulse'])['total protein'].transform('median'), inplace=True)

In [12]:
df

,surgery,Age,Hospital Number,rectal temperature,pulse,respiratory rate,temperature of extremities,peripheral pulse,mucous membranes,capillary refill time,...,packed cell volume,total protein,abdominocentesis appearance,abdomcentesis total protein,outcome,surgical lesion,type of lesion1,type of lesion2,type of lesion3,cp_data
0,2.0,1,530101,38.500000,66.0,28.0,3.0,3.0,NaN,2.0,...,45.0,8.400000,NaN,NaN,2.0,2,11300,0,0,2
1,1.0,1,534817,39.200000,88.0,20.0,NaN,NaN,4.0,1.0,...,50.0,85.000000,2.0,2.0,3.0,2,2208,0,0,2
2,2.0,1,530334,38.300000,40.0,24.0,1.0,1.0,3.0,1.0,...,33.0,6.700000,NaN,NaN,1.0,2,0,0,0,1
3,1.0,9,5290409,39.100000,164.0,84.0,4.0,1.0,6.0,2.0,...,48.0,7.200000,3.0,5.3,2.0,1,2208,0,0,1
4,2.0,1,530255,37.300000,104.0,35.0,NaN,NaN,6.0,2.0,...,74.0,7.400000,NaN,NaN,2.0,2,4300,0,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
295,1.0,1,533886,38.167917,120.0,70.0,4.0,NaN,4.0,2.0,...,55.0,65.000000,NaN,NaN,3.0,2,3205,0,0,2
296,2.0,1,527702,37.200000,72.0,24.0,3.0,2.0,4.0,2.0,...,44.0,24.456929,3.0,3.3,3.0,1,2208,0,0,1
297,1.0,1,529386,37.500000,72.0,30.0,4.0,3.0,4.0,1.0,...,60.0,6.800000,NaN,NaN,2.0,1,3205,0,0,2
298,1.0,1,530612,36.500000,100.0,24.0,3.0,3.0,3.0,1.0,...,50.0,6.000000,3.0,3.4,1.0,1,2208,0,0,1
299,1.0,1,534618,37.200000,40.0,20.0,NaN,NaN,NaN,NaN,...,36.0,62.000000,1.0,1.0,3.0,2,6112,0,0,2